# Generated by Django 4.2.5 on 2024-05-03 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание мероприятия')),
                ('time', models.DateTimeField()),
                ('duration', models.FloatField(verbose_name='Продолжительность(в часах)')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('seats_amount', models.IntegerField(verbose_name='Количество мест')),
                ('available_seats', models.IntegerField(default=models.IntegerField(verbose_name='Количество мест'), verbose_name='Количество доступных мест')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categoryevent')),
            ],
        ),
    ]
