# Generated by Django 4.2.5 on 2024-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_type_event_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='field_name',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/'),
        ),
    ]
