# Generated by Django 4.2.5 on 2024-05-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_field_name_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='Организация', max_length=255, verbose_name='Организаторы'),
        ),
    ]
