# Generated by Django 4.2.5 on 2024-05-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_eventuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventUser',
        ),
    ]
