# Generated by Django 4.2.5 on 2024-05-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_eventuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.IntegerField(verbose_name='Доступное количество мест'),
        ),
    ]
